### ISSUE TITLE
Empty string literal on the same line as a string literal

### ISSUE THREAD

**Issue by jayvdb** [PyCQA/pep8#424]
This may be outside the scope of pep8, but it feels like it is almost a syntax error.

The following is a syntax error:
```
'''blah'
```

However the following is neither a syntax error or a pep8 error:
```
'blah'''
```

This is almost a special case of #37, where there can be no meaning or purpose for the trailing string literal.

**Comment by sigmavirus24** [comment]
So you want pep8 to raise a warning/error on valid python?

```py
s = 'blah'''
print(s == 'blah')  # True
s = 'blah''blah'
print(s)  # blahblah
```

pep8 is about style. This aligns more with the check for unused imports in pyflakes. Even so, let's look at how the `ast` sees this:

```py
>>> code = "foo = 'blah'''"
>>> code
"foo = 'blah'''"
>>> import ast
>>> parsed = ast.parse(code)
>>> parsed
<_ast.Module object at 0x1032a1e10>
>>> parsed.body
[<_ast.Assign object at 0x1032ff690>]
>>> parsed.body[0]
<_ast.Assign object at 0x1032ff690>
>>> parsed.body[0].value
<_ast.Str object at 0x1032ff710>
>>> parsed.body[0].value.s
'blah'
>>> code = "foo = 'blah''blah'"
>>> parsed = ast.parse(code)
>>> parsed.body
[<_ast.Assign object at 0x1032ff790>]
>>> parsed.body[0].value
<_ast.Str object at 0x1032ff850>
>>> parsed.body[0].value.s
'blahblah'
```

Note that it sees the assignment value as being a single string in both cases. This is how the interpreter views the code.

While this may *look* odd or cause confusion, the code is neither syntactically incorrect, nor prohibited by the document. A stylistic check for this could be written as an extension to flake8.

**Comment by jayvdb** [comment]
pep8 raises lots of errors on valid Python.

Of your example code, it is only the first line which I believe could fit within the scope of pep8.  While pep8 isnt explicit on this, I believe it is heavily implied by the 'string quotes' section.

Line 3 of your example code, concatenating two non-empty strings, is of course not a noop, and not part of my raised issue.

Appreciate that you might not agree it fits within pep8.  Are there no other rules in the pep8 package which reject stupid syntax which isnt literally prohibited in the pep?

I've seen this occur often enough that a solution is needed; if not pep8, then I am happy to look elsewhere or build a flake8 extension to do the trick.

**Comment by sigmavirus24** [comment]
> pep8 raises lots of errors on valid Python.

The difference being that most them are in PEP-0008 (or were and have since been edited out)

> I believe it is heavily implied by the 'string quotes' section

pep8 has in the past created warnings/errors based on different people's readings of what is heavily implied and what isn't. This is why some people absolutely hate the tool and the rules included. They think it goes too far. I don't think we should continue to make that mistake or force the PEP-0008 authors to update the document to either agree or disagree with the tool.

> Line 3 of your example code, concatenating two non-empty strings, is of course not a noop, and not part of my raised issue.

Right. My point is that they do exactly the same thing. In your example you're concatenating an empty string with a non-empty one. Line 3 shows that this is the intended behaviour of the interpreter which is why I don't think we should be doing anything with your example.

> Are there no other rules in the pep8 package which reject stupid syntax which isnt literally prohibited in the pep?

Honestly, I can't think of any. We recommend against things like `if not foo == bar` or tell people to write `if foo is not bar` instead of `if not foo is bar`. Those are in the PEP though.

> I've seen this occur often enough that a solution is needed

Between working on OpenStack and the projects that I work on outside of OpenStack, I've never seen this in code someone has submitted. Even so, it's not really a PEP-0008 style issue and it's certainly not syntactically incorrect.

If you see this in one of your projects specifically, I would advise keeping this local to that project. For example, if you're seeing this in wikibot, you could have a submodule called `pep8ext` and then in your entry-points add:

```py
'flake8.extension': ['WB10 = wikibot.pep8ext.noop_string_concat'],
```

That will install the check for your project, e.g., if you use `tox` to run your pep8 checks, e.g.,

```ini
# tox.ini
[testenv:flake8]
deps = flake8
       flake8-docstrings
       flake8-import-order
command = flake8
```

Since tox installs the project in question, it'll add that entry-point and it will allow you to run flake8 against that project with the extension in question.

**Comment by jayvdb** [comment]
Closing as project maintainers do not consider it within scope of this project.
