### ISSUE TITLE
Update repository link in docs

### ISSUE THREAD

**Issue by petebachant** [PyCQA/pep8#437]
In IPython I run

```
In [23]: pep8?
Type:        module
String form: <module 'pep8' from 'C:\\Users\\Pete\\Anaconda3\\lib\\site-packages\\pep8.py'>
File:        c:\users\pete\anaconda3\lib\site-packages\pep8.py
Docstring:
Check Python source code formatting, according to PEP 8.

For usage and a list of options, try this:
$ python pep8.py -h

This program and its regression test suite live here:
http://github.com/jcrocholl/pep8

Groups of errors and warnings:
E errors
W warnings
100 indentation
200 whitespace
300 blank lines
400 imports
500 line length
600 deprecation
700 statements
900 syntax error
```

and the link is incorrect. Changing the protocol to https redirects properly though.

**Comment by IanLee1521** [comment]
Hi @petebachant, this was updated in https://github.com/PyCQA/pep8/blob/145e2a87a987178679e39eebf2230e68e200db38/pep8.py#L34 to point to the new organization. That said I will also point to https instead of http. (That said, for me the redirection is working with or without the 's' and with either jcrocholl or pycqa)
