### ISSUE TITLE
W503 erroneously raised on PEP8 spec "acceptable" if statements

### ISSUE THREAD

**Issue by rtilder** [PyCQA/pep8#475]
I'm getting W503 warnings on if statements in the following style:

```
if (this
        or that)
```

While this is against the rule on binary operators, it is explicitly mentioned as acceptable in the paragraph on if statements in the [Indentation](https://www.python.org/dev/peps/pep-0008/#indentation) section of the spec.

**Comment by sigmavirus24** [comment]
I suspect you're referring to:

```py
# Add some extra indentation on the conditional continuation line.
if (this_is_one_thing
        and that_is_another_thing):
    do_something()
```

Specifically? If so, that looks like one of the examples that was not corrected when they specified that binary operators should be on the first line. Regardless, if you dislike the check please disable it. We're not the boss of you.

Otherwise, you have an issue with the document and should have it fixed appropriately there by someone else (since none of us are committers to the PEP repository or authors of the document).
